---

 - name: Install common software
   yum:
     name: "{{ packages }}"
     state: latest
     update_cache: yes
   vars:
     packages:
       - vim
       - htop
       - mc
       - epel-release

 - name: Change timezone to Europe/Moscow
   timezone:
     name: Europe/Moscow


