---

- hosts: balancer

  - name: Accept HTTP
   firewalld:
     service: http
     permanent: yes
     state: enabled
   notify:
     - firewalld_restart

 - name: Accept HTTPS
   firewalld:
     service: https
     permanent: yes
     state: enabled
   notify:
     - firewalld_restart
 
 - name: Accept SSH from admin host {{ admin_host }}
   firewalld:
     rich-rule: rule family=ipv4 source address={{ admin_host }} service name="ssh" accept
     permanent: yes
     state: enabled
   notify:
     - firewalld_restart

 - name: Accept zabbix monitoring
    firewalld:
      rich-rule: rule family=ipv4 source address={{ zabbix_host }} port port={{ zabbix_port }} accept
      permanent: yes
      state: enabled
    notify:
      - firewalld_restart