---

- hosts: balancer 

  - name: Install Nginx
    yum:
      name: nginx
      state: latest


  - name: Copy origin config
    command: mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.origin

  - name: Generate config
    template:
      src: ../templates/nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: 0644
    notify:
      - nginx_restart

  - name: Enable service nginx
    service:
      name: nginx
      enabled: yes

