---

- name: firewalld_restart
  systemd:
    name: firewalld
    state: reloaded

- name: zabbix_agent_restart
  command: systemctl restart zabbix-agent

- name: httpd_restart
  systemd:
    name: httpd
    state: reloaded

- name: nginx_restart
  systemd:
    name: nginx
    state: reloaded
